// <auto-generated />
using System;
using Mailroom_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mailroom_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220811192728_ShipmentUpdate")]
    partial class ShipmentUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Mailroom_API.Models.LetterBag", b =>
                {
                    b.Property<string>("BagNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("LetterCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(20,2)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(20,3)");

                    b.HasKey("BagNo");

                    b.ToTable("LetterBags");
                });

            modelBuilder.Entity("Mailroom_API.Models.Parcel", b =>
                {
                    b.Property<string>("ParcelNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("LetterBagBagNo")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ParcelBagBagNo")
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(20,2)");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(20,3)");

                    b.HasKey("ParcelNumber");

                    b.HasIndex("LetterBagBagNo");

                    b.HasIndex("ParcelBagBagNo");

                    b.ToTable("Parcels");
                });

            modelBuilder.Entity("Mailroom_API.Models.ParcelBag", b =>
                {
                    b.Property<string>("BagNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("BagNo");

                    b.ToTable("ParcelBags");
                });

            modelBuilder.Entity("Mailroom_API.Models.Shipment", b =>
                {
                    b.Property<string>("ShipmentNo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("BagList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FlightDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlightNo")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("bit");

                    b.HasKey("ShipmentNo");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("Mailroom_API.Models.Parcel", b =>
                {
                    b.HasOne("Mailroom_API.Models.LetterBag", null)
                        .WithMany("ParcelCollection")
                        .HasForeignKey("LetterBagBagNo");

                    b.HasOne("Mailroom_API.Models.ParcelBag", null)
                        .WithMany("ParcelCollection")
                        .HasForeignKey("ParcelBagBagNo");
                });

            modelBuilder.Entity("Mailroom_API.Models.LetterBag", b =>
                {
                    b.Navigation("ParcelCollection");
                });

            modelBuilder.Entity("Mailroom_API.Models.ParcelBag", b =>
                {
                    b.Navigation("ParcelCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
